# Generated by Django 4.1.5 on 2023-01-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='short_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
