# Generated by Django 4.1.5 on 2023-01-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerApp', '0002_shorturl_short_url_alter_shorturl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='count_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.URLField(),
        ),
    ]
