# Generated by Django 4.1.5 on 2023-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerApp', '0003_shorturl_count_visits_alter_shorturl_short_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
