# Generated by Django 4.1.5 on 2023-01-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortenerApp', '0004_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='count_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
